author_name: Marek Chrapek
author_subtitle: Technical leader | Conference speaker | Professional trainer | mergeIT meetup lead
author_avatar: https://github.com/mchrapek.png
author_bio: >
  Tech lead, trainer, deeply involved with JVM languages from the beginning, 
  with adventures in front-end development. An active member of the Silesian IT 
  community and founder of the merge IT meetup.
author_github: mchrapek
author_linkedin: marek-chrapek
